karyasampadan/urls.py
from django.conf.urls import url


from .views import MonthlyControlList, MonthlyProgressList, MonthlyProgressCreateView, MonthlyProgressDetail, MonthlyKaryakramCreateView, MonthlyChildKaryakramCreateView

app_name = 'karyasampadan'

urlpatterns = [
    url(r'^monthlylist/(?P<office>[0-9]+)/$', MonthlyControlList.as_view(), name='monthly-control-list'),
    url(r'^monthlyallprogresslist/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressList.as_view(), name='monthly-all-progress-list'),
    url(r'^addmonthlypragati/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/(?P<month_id>[0-9]+)/$', MonthlyProgressCreateView.as_view(), name='add-monthly-pragati'),
    url(r'^monthlyprogressdetail/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyProgressDetail.as_view(), name='monthly-progress-detail'),    
    url(r'^monthlykaryasampadan/create/(?P<office>[0-9]+)/$', MonthlyKaryakramCreateView.as_view(), name='monthly-karyasampadan-add'),
    url(r'^monthlykaryasampadan/create/child/(?P<office>[0-9]+)/(?P<karyakram_id>[0-9]+)/$', MonthlyChildKaryakramCreateView.as_view(), name='monthly-karyasampadan-add-child'),
    
        ]

mole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    # url(r'^sachibbaithak/', include("sachibBaithak.urls", namespace="sachibBaithak")),
    # url(r'^karyasampadan/', include("karyasampadan.urls", namespace="karyasampadan")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^forms/', include("forms.urls", namespace="forms")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

office/urls.py
from django.conf.urls import url


from office.views import  OfficeDetailView, \
    OfficeUserView, OfficeBudgetUpdateView

app_name = 'office'

from office.views import OfficeCreateView, OfficeListView, OfficeUpdateView, OfficeDeleteView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, Monthly, OfficeDashboard, DistrictDashboard, ProfileDetailView, ProfileUpdateView, OfficeKaryakramList,\
    OfficeViewDataDetail, OfficePragati


urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/pragati/(?P<pk>[0-9]+)/$', OfficePragati.as_view(), name='office-pragati'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/view-data-detail/(?P<pk>[0-9]+)/$', OfficeViewDataDetail.as_view(), name='view-data-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakramlist/$', OfficeKaryakramList.as_view(), name='office-karyakram-list'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    
    url(r'^office/addbudget/(?P<pk>[0-9]+)/$', OfficeBudgetUpdateView.as_view(), name='office-budget-update'),
    url(r'^deactivate_user/$', ProfileUpdateView.as_view(), name='deactivate-users'),
    url(r'^office/users/profile_update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^office/users/profile_detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^office/monthly/$', Monthly.as_view(), name='monthly-report'),
    

        ]

progressmonitoring/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from supa import views as core_views

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^supa/', include('supa.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'registration/Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registration/Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'registration/Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', core_views.firstlogin, name='firstlogin'),    
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

karyasampadan/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from reports.models import Office, FiscalYear, Months, KaryaKram, OfficeSetting


from django.db import models

class SampadanKaryakram(models.Model):
    main_suchak = models.ForeignKey('self', verbose_name="मुख्य सूचक", blank=True, null=True, related_name="karyasampadan_parent", help_text="")
    name = models.CharField(max_length=255, verbose_name="सूचक",)
    office = models.ForeignKey(Office, verbose_name="निकाय")
    fiscal_year = models.ForeignKey(FiscalYear, verbose_name="वित्तीय वर्ष")

    def get_monthly_progress(self):
        #assign ofice fiscal year on office create
        fiscal_year=OfficeSetting.objects.get(office=self.office, is_active=True).fiscal_year
        return self.sampadan_monthlyprogress.filter(fiscal_year=fiscal_year).order_by('-month_id')
        # fiscal_year=self.office.OfficeSetting.fiscal_year
        #      return self.sampadan_monthlyprogress.filter(fiscal_year=fiscal_year).order_by('-month_id')
        #        
class SampadanMonthlyProgress(models.Model):
    sampadankaryakram = models.ForeignKey(SampadanKaryakram, verbose_name=" कार्यक्रम", related_name="sampadan_monthlyprogress", help_text="")
    fiscal_year = models.ForeignKey(FiscalYear, verbose_name="वित्तीय वर्ष")
    month=models.ForeignKey(Months)
    pragati = models.TextField(verbose_name="महिनाको प्रगती")
    pragati_till_date = models.TextField(verbose_name="हाल सम्मको प्रगती")
    comments = models.TextField(verbose_name="कैफियत")
    datesubmited = models.CharField(max_length=255, null=True, blank=True)
    dateupdated = models.CharField(max_length=255, null=True, blank=True)
 

karyasampadan/forms.py
from django import forms

from .models import SampadanKaryakram, SampadanMonthlyProgress


class MonthlyProgressForm(forms.ModelForm):

    class Meta:
        model = SampadanMonthlyProgress
        exclude = ('id','sampadan_karyakram', 'month', 'fiscal_year', 'datesubmited', 'dateupdated', 'pragati_till_date')


class MonthlyKaryasampadanForm(forms.ModelForm):

   
    class Meta:
        model = SampadanKaryakram
        exclude = ('main_suchak', 'office', )



class MonthlyChildKaryasampadanForm(forms.ModelForm):

    class Meta:
        model = SampadanKaryakram
        exclude = ('main_suchak', 'office',)
    

karyasampadan/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render
import datetime

from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import View
from django.views.generic import FormView, ListView, TemplateView
from office.models import Office
from django.db.models import Prefetch
from karyasampadan.models import SampadanKaryakram, SampadanMonthlyProgress
from karyasampadan.forms import MonthlyProgressForm, MonthlyKaryasampadanForm, MonthlyChildKaryasampadanForm
from userrole.mixins import CreateView, OfficeView, OfficerMixin, UpdateView
from django.views.generic.edit import CreateView as BaseCreateView
from django.core.urlresolvers import reverse
from reports.npdateconverter import NepaliDateConverter
from django.contrib import messages
from django.contrib.auth.models import User
from notifications.signals import notify
from channels import Group
import json
from reports.models import Months

class MonthlyProgressView(object):
    model = SampadanMonthlyProgress
    form_class = MonthlyProgressForm

class MonthlyKaryasampadanView(object):
    model = SampadanKaryakram
    form_class = MonthlyKaryasampadanForm


class MonthlyControlList(OfficeView, OfficerMixin, MonthlyKaryasampadanView, ListView):
    template_name = 'karyasampadan/monthly_control.html'

    def get_context_data(self,  **kwargs):
        data = super(MonthlyControlList, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        data['office_obj'] = Office.objects.get(pk=self.kwargs.get('office'))
        return data

    def get_queryset(self):

        qs =  super(MonthlyControlList, self).get_queryset().filter(main_suchak__isnull=True).prefetch_related(Prefetch('karyasampadan_parent__sampadan_monthlyprogress', queryset=SampadanMonthlyProgress.objects.order_by('-month__id')))
        return qs

class MonthlyKaryakramCreateView(OfficeView, MonthlyKaryasampadanView, CreateView):
    template_name = "karyasampadan/karyakram_form.html"
    def get_success_url(self):
        return reverse('karyasampadan:monthly-control-list', args=(self.object.office.id,))

class MonthlyChildKaryakramCreateView(OfficeView, MonthlyKaryasampadanView, CreateView):
    form_class = MonthlyChildKaryasampadanForm
    template_name = "karyasampadan/karyakram_form.html"
    def form_valid(self, form):
        super(MonthlyChildKaryakramCreateView, self).form_valid(form)
        form.instance.main_suchak = SampadanKaryakram.objects.get(pk=self.kwargs.get('karyakram_id'),)
        self.object = form.save()
        return redirect(reverse('karyasampadan:monthly-control-list', args=(self.object.office.id,)))

    def get_success_url(self):
        return reverse('karyasampadan:monthly-control-list', args=(self.object.office.id,))

class MonthlyProgressList(OfficeView, OfficerMixin, TemplateView):
    template_name = 'karyasampadan/monthly_all_progress_list.html'

    def get_context_data(self,  **kwargs):
        data = super(MonthlyProgressList, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        data['office_obj'] = Office.objects.get(pk=self.kwargs.get('office'))
        data['karyakram'] = SampadanKaryakram.objects.get(pk=self.kwargs.get('karyakram_id'))
        karyakram_id = self.kwargs.get('karyakram_id')
        data['months'] = Months.objects.raw('SELECT * FROM reports_months LEFT JOIN karyasampadan_sampadanmonthlyprogress ON reports_months.id = karyasampadan_sampadanmonthlyprogress.month_id AND karyasampadan_sampadanmonthlyprogress.sampadankaryakram_id = %s', [karyakram_id])
        return data

class MonthlyProgressCreateView(OfficeView, MonthlyProgressView, UpdateView):
    template_name = 'karyasampadan/monthlyprogress_form.html'
    def get_object(self):
        month_id = self.kwargs['month_id']
        karyakram_id = self.kwargs['karyakram_id']
        monthly_pragati, created = SampadanMonthlyProgress.objects.get_or_create(sampadankaryakram_id=karyakram_id, fiscal_year_id=1, month_id=month_id)
        return monthly_pragati


    def get_success_url(self):
        converter = NepaliDateConverter()
        self.object.dateupdated = converter.ad2bs((datetime.date.today().year, datetime.date.today().month, datetime.date.today().day))
        if self.object.datesubmited is None:
            self.object.datesubmited = converter.ad2bs((datetime.date.today().year, datetime.date.today().month, datetime.date.today().day))
        self.object.save()
        return reverse('karyasampadan:monthly-all-progress-list',args=(self.object.sampadankaryakram.office.id, self.object.sampadankaryakram.id))

class MonthlyProgressDetail(OfficeView, OfficerMixin, TemplateView):
    template_name = 'karyasampadan/monthly_progress_detail.html'

    def get_context_data(self,  **kwargs):
        data = super(MonthlyProgressDetail, self).get_context_data(**kwargs)
        data['office'] = self.kwargs.get('office')
        data['office_obj'] = Office.objects.get(pk=self.kwargs.get('office'))
        karyakram = SampadanKaryakram.objects.get(pk=self.kwargs.get('karyakram_id'))
        # if  karyakram.get_monthly_progress().first():
        #     a = karyakram.get_monthly_progress().first().month_id
        # else:
        #     a = 0
        data['history'] = karyakram.get_monthly_progress()
        data['karyakram'] = karyakram
        karyakram_id = self.kwargs.get('karyakram_id')
        data['months'] = Months.objects.raw('SELECT * FROM reports_months LEFT JOIN reports_monthlyprogress ON reports_months.id = reports_monthlyprogress.month_id AND reports_monthlyprogress.karyakram_id = %s', [karyakram_id])
        return data

templates/karyasampadan/monthly_all_progress_list.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}मासिक कार्यक्रम{% endblock title %}
{% block extra_css %}

  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 

   <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>
{% endblock extra_css %}
{% block content %}

<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			    <li><a href="{% url 'dashboard' %}">गृह पृष्ठ</a></li>
                <li><a href="{% url 'office:office-dashboard' office %}">{{office_obj.name}}</a></li>
                <li class="active">कार्यक्रम</li>
			</ol>
			<div class="bg-white padding margin-top-lg">

                 <h2>मासिक प्रगतिहरु</h2>

              

				<div class="table-responsive">
					<table id="datatable" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>क्र. म.</th>
								<th>महिना</th>
								<th>महिनाको प्रगती</th>
								<th>कैफियत</th>
								<th>थप्नुहोस</th>
							</tr>
							
						</thead>
						<tbody>
                        {% for month in months %}

							<tr>
								<td>{{ month.id}}</td>
								<td>{{ month.month }}</td>
								<td>
								{% if month.pragati == None %}
								
								हाल  सम्म भरिएको छैन |

								{% else %}

								{{ month.pragati }}
								{% endif %}
								</td>
								<td>
								{% if month.pragati_till_date == None %}
	हाल  सम्म भरिएको छैन |
								{% else %}
								{{ month.comments }}
								{% endif %}
								</td>
								<td>
								{% if month.pragati == None %}
								
								<a href="{% url 'karyasampadan:add-monthly-pragati' office_obj.id karyakram.id month.id %}">Add.</a>

								{% else %}
								{% if request.office %}
								{% else %}
								<a href="{% url 'karyasampadan:add-monthly-pragati' office_obj.id karyakram.id month.id %}">Edit.</a>
								{% endif %}
								{% endif %}
								</td>
							</tr>
                             
                        {% endfor %}


						</tbody>
					</table>
				</div>
				
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->

{% endblock content %}

{% block extra_scripts %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        "ordering": false,
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_scripts %}

templates/karyasampadan/monthly_control.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}कार्य सम्पादन सुचक{% endblock title %}
{% block extra_css %}

  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 

   <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>
{% endblock extra_css %}
{% block content %}

<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			    <li><a href="{% url 'dashboard' %}">गृह पृष्ठ</a></li>
                <li><a href="{% url 'office:office-dashboard' office %}">{{office_obj.name}}</a></li>
                <li class="active">कार्यक्रमहरु</li>
			</ol>
			<div class="bg-white padding margin-top-lg">

                 <h4>सम्पूर्ण कार्यक्रमहरु  <a href="{% url 'karyasampadan:monthly-karyasampadan-add' office %}" class="btn btn-xs btn-primary pull-right">
                 <i class="fa fa-plus-circle" aria-hidden="true">  मूल कार्यक्रम थप्नुहोस </i></a></h4>
        
       

				<div class="table-responsive">
					<table id="datatable" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>क्र. म.</th>
								<th>कार्य विवरण</th>
								<th>महिना</th>
								<th>महिनाको प्रगती</th>
								<th>हाल सम्मको प्रगती</th>
								<th>कैफियत</th>
								<th>थप्नुहोस</th>
							</tr>
							
						</thead>
						<tbody>
                        {% for karyakram in object_list %}

							<tr>
								<td>{{ karyakram.id }}</td>
								<td>{{ karyakram.name }}</td>
								<td></td>
								<td></td>
								<td></td>
								<td></td>
								<td><a href="{% url 'karyasampadan:monthly-karyasampadan-add-child' karyakram.office.id karyakram.id %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-plus"></i></a></td>
							</tr>
                             {% if karyakram.karyasampadan_parent %}
                                 {% for subkaryakrams in karyakram.karyasampadan_parent.all %}

                                    <tr>
                                    <td><span class="glyphicon glyphicon-arrow-right"></span> {{ karyakram.id }}.{{ forloop.counter }}</td>
                                        <td>{{ subkaryakrams.name }}</td>

                                        {% for monthlydata in subkaryakrams.sampadan_monthlyprogress.all|slice:":1" %}
                                        <td>{{ monthlydata.month }}</td>
                                        <td>{{ monthlydata.pragati }}</td>
                                        <td><a href="{% url 'karyasampadan:monthly-progress-detail' karyakram.office.id subkaryakrams.id %}" title="" class="btn btn-xs btn-primary"></i>हाल सम्मको प्रगती</a></td>
                                        <td>{{ monthlydata.comments }}</td>
                                        {% empty %}
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        <td></td>
                                        {% endfor %}
                                        
                                        <td><a href="{% url 'karyasampadan:monthly-all-progress-list' karyakram.office.id subkaryakrams.id %}" title="" class="btn btn-xs btn-primary"><i class="glyphicon glyphicon-eye-open"></i></a></td>
                                         
                                    </tr>
                                {% endfor %}
                            {% endif %}
                        {% endfor %}


						</tbody>
					</table>
				</div>
			
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->

{% endblock content %}
{% block extra_scripts %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        "ordering": false,
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_scripts %}

templates/karyasampadan/monthly_progress_detail.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}कार्य सम्पादन सुचक{% endblock title %}
{% block extra_css %}

  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 

   <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>
{% endblock extra_css %}
{% block content %}

<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb no-margin margin-top-lg">
			    <li><a href="{% url 'dashboard' %}">गृह पृष्ठ</a></li>
                <li><a href="{% url 'office:office-dashboard' office %}">{{office_obj.name}}</a></li>
                <li><a href="{% url 'karyasampadan:monthly-control-list' office %}">कार्यक्रमहरु</a></li>
                <li class="active">हाल सम्मको प्रगती</li>
			</ol>
			<div class="bg-white padding margin-top-lg">

               

				<div class="table-responsive">
					<table id="datatable" class="table table-bordered table-hover">
						<thead>
							<tr>
								
								<th>हाल सम्मको प्रगती</th>
								
							</tr>
							
						</thead>
						<tbody>
                    		{% for month in history %}
							<tr>
								<th>
								 	<span class="glyphicon glyphicon-arrow-right"></span> {{ month.pragati }}
								</th>
							</tr>
							{% endfor %}
						</tbody>
					</table>
				</div>
			
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->

{% endblock content %}
{% block extra_scripts %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        "ordering": false,
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_scripts %}