mole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    # url(r'^sachibbaithak/', include("sachibBaithak.urls", namespace="sachibBaithak")),
    # url(r'^karyasampadan/', include("karyasampadan.urls", namespace="karyasampadan")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^forms/', include("forms.urls", namespace="forms")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

office/urls.py
from django.conf.urls import url


from office.views import  OfficeDetailView, \
    OfficeUserView, OfficeBudgetUpdateView

app_name = 'office'

from office.views import OfficeCreateView, OfficeListView, OfficeUpdateView, OfficeDeleteView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, Monthly, OfficeDashboard, DistrictDashboard, ProfileDetailView, ProfileUpdateView, OfficeKaryakramList,\
    OfficeViewDataDetail, OfficePragati


urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/pragati/(?P<pk>[0-9]+)/$', OfficePragati.as_view(), name='office-pragati'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/view-data-detail/(?P<pk>[0-9]+)/$', OfficeViewDataDetail.as_view(), name='view-data-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakramlist/$', OfficeKaryakramList.as_view(), name='office-karyakram-list'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    
    url(r'^office/addbudget/(?P<pk>[0-9]+)/$', OfficeBudgetUpdateView.as_view(), name='office-budget-update'),
    url(r'^deactivate_user/$', ProfileUpdateView.as_view(), name='deactivate-users'),
    url(r'^office/users/profile_update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^office/users/profile_detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^office/monthly/$', Monthly.as_view(), name='monthly-report'),
    

        ]

progressmonitoring/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from supa import views as core_views

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^supa/', include('supa.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'registration/Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registration/Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'registration/Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', core_views.firstlogin, name='firstlogin'),    
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

sachibBaithak/urls.py
from django.conf.urls import url
from sachibBaithak.views import BudgetBaktabyaListView, BudgetBaktabyaCreateView, BudgetBaktabyaUpdateView, SachibBaithakCreateView, SachibBaithakmainUpdateView, SachibBaithakMainCreateView,SachibBaithakListView, SachibBaithakadminUpdateView, SachibBaithakMainListView, SachibBaithakuserUpdateView
app_name = 'sachibBaithak'

urlpatterns = [
    url(r'^create/(?P<office>[0-9]+)/(?P<main_id>[0-9]+)/$', SachibBaithakCreateView.as_view(), name='sachibbaithak-create'),
    url(r'^maincreate/(?P<office>[0-9]+)/$', SachibBaithakMainCreateView.as_view(), name='sachibbaithak-main-create'),
    url(r'^mainupdate/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', SachibBaithakmainUpdateView.as_view(), name='sachibbaithak-main-update'),
    url(r'^mainlist/(?P<office>[0-9]+)/$', SachibBaithakMainListView.as_view(), name='sachibbaithak-main-list'),
    url(r'^baithaklist/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', SachibBaithakListView.as_view(), name='sachibbaithak-list'),
    url(r'^adminupdate/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', SachibBaithakadminUpdateView.as_view(), name='sachibbaithak-admin-update'),
    url(r'^userupdate/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', SachibBaithakuserUpdateView.as_view(), name='sachibbaithak-user-update'),
    url(r'^budgetbaktabyalist/(?P<office>[0-9]+)/$', BudgetBaktabyaListView.as_view(), name='budgetbaktabya-list'),
    url(r'^budgetbaktabya/create/(?P<office>[0-9]+)/$', BudgetBaktabyaCreateView.as_view(), name='budgetbaktabya-create'),
    url(r'^budgetbaktabya/update/(?P<office>[0-9]+)/(?P<pk>[0-9]+)/$', BudgetBaktabyaUpdateView.as_view(), name='budgetbaktabya-update'),
    
   ]

templates/budgetbaktabya/all_budgetbaktabya_list.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}

{% block title %}बजेट बक्तब्य{% endblock title %}
{% block extra_css %}

  <link rel="stylesheet" href="{% static 'plugins/datatables/dataTables.bootstrap.css' %}"> 
  <link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.dataTables.min.css"> 

   <style type="text/css">                                              
  #div2 {
    white-space: nowrap;
    width: 20em;
    overflow: hidden;
    text-overflow: ellipsis;

}</style>
{% endblock extra_css %}
{% block content %}


		<!--Main Content Area Starts-->
		<section id="app-section">
			<ol class="breadcrumb">
                <li><a href="{% url 'dashboard' %}"></i>गृह पृष्ठ</a></li>
                <li><a href="{% url 'office:office-dashboard' office.id %}">{{ office.name }}</a></li>
                <li class="active">बजेट बक्तब्य</li>
              </ol>
			<div class="bg-white padding margin-top-lg">
				<div class="app-page-header">
					<div class="row">
						<div class="col-md-10">
							<h4>बजेट बक्तब्य</h4>
						</div>

						<div class="col-md-2">
							<div class="action-holder">
								<a href="{% url 'sachibBaithak:budgetbaktabya-create' office.id %}" title="" class="btn btn-xs btn-primary"><i class="fa fa-plus-circle"></i>  बजेट बक्तब्य थप्नुहोस</a>
								
							</div>
						</div>
					</div>
				</div>

				<div class="table-responsive">
					<table id="datatable" class="table table-bordered table-hover">
						<thead>
							<tr>
								<th>बजेट वक्तव्यको बुदाँ नं.</th>
								<th>नीति तथा कार्यक्रमको व्यहोरा</th>
								<th>प्रगति/कार्यान्वयनको अवस्था (भौतिक एवं वित्तिय दुवै)</th>
								<th>समस्याहरु</th>
								<th>सुधारका उपायहरु</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						{% for data in object_list %}
							<tr>
								<td>{{ data.budhano }}</td>
								<td>
								{{ data.karyakrams }}
								</td>
								<td>
								{{ data.pragati }}
								</td>
								<td>
								{{ data.problems }}
								</td>
								<td>
								{{ data.solutions }}
								</td>
								
								<td>
								<a href="{% url 'sachibBaithak:budgetbaktabya-update' office.id data.id %}
								
								" title="" class="btn btn-xs btn-primary"><i class="fa fa-edit"></i></a>

								</td>
							</tr>
						{% endfor %}
							

						</tbody>
						
					</table>
				</div>
				
			</div>
		</section>
		<div class="clearfix"></div>
		<!--Main Content Area Ends-->


{% endblock content %}
{% block extra_scripts %}
<script src="{% static 'plugins/datatables/jquery.dataTables.min.js' %}"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.flash.min.js"></script>
<script src = "https://cdnjs.cloudflare.com/ajax/libs/jszip/3.1.3/jszip.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/pdfmake.min.js"></script>
<script src = "https://cdn.rawgit.com/bpampuch/pdfmake/0.1.27/build/vfs_fonts.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.html5.min.js"></script>
<script src = "https://cdn.datatables.net/buttons/1.3.1/js/buttons.print.min.js"></script>
<script src="{% static 'plugins/datatables/dataTables.bootstrap.min.js' %}"></script>
<script>
  $(function () {
    $("#datatable").DataTable(
      {
        scrollX: true,
        dom: 'Bfrtip',
        "ordering": false,
        lengthMenu: [
            [ 10, 25, 50, -1 ],
            [ '10 rows', '25 rows', '50 rows', 'Show all' ]
        ],
        buttons: [
            'pageLength','copy', 'csv', 'excel', 'pdf', 'print',
        ]
      });
    });
</script>
{% endblock extra_scripts %}

templates/budgetbaktabya/budgetbaktabya_form.html
{% extends "base_layout.html" %}
{% load staticfiles %}
{% load filters %}


{% block title %}बजेट बक्तब्य{% endblock title %}

{% block content %}
    <section id="app-section">
        <section class="content-header">
              <ol class="breadcrumb">
                <li><a href="{% url 'dashboard' %}"></i>गृह पृष्ठ</a></li>
                <li><a href="{% url 'office:office-dashboard' office.id %}">{{ office.name }}</a></li>
                <li class="active">बजेट बक्तब्य</li>
              </ol>
        </section>

        <h2>बजेट बक्तब्य</h2>
        <form class = "" action="" method="post" enctype="multipart/form-data">
            {% csrf_token %}

            {% for field in form %}
              
			<div class="form-group">
				<div class="col-sm-offset-2 col-sm-10">
					<span class="text-danger small">{{ field.errors }}</span>
				</div>
				<label class="col-md-3 control-label">{{ field.label_tag }}</label>
				<div class="col-md-5">{{ field }}</div>
			</div>
		      {% endfor %}


            <div class="form-group">
                <div class="col-sm-offset-2 col-sm-10">
                    <button type="submit" class="btn btn-success">पेश गर्नुहोस्</button>
                </div>
            </div>

        </form>
    </section>
{% endblock content %}


{% block extra_script %}
<script>



 $(document).ready(function(){
       $('[form="form"]').addClass('form-control input-md');

  }


</script>
{% endblock extra_script %}