mole/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.conf import settings
from django.conf.urls.static import static
from office.views import DashboardView
urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^users/', include("users.urls", namespace="users")),
    url(r'^reports/', include("reports.urls", namespace="reports")),
    url(r'', include("office.urls", namespace="office")),
    url(r'^userrole/', include("userrole.urls", namespace="role")),
    # url(r'^sachibbaithak/', include("sachibBaithak.urls", namespace="sachibBaithak")),
    # url(r'^karyasampadan/', include("karyasampadan.urls", namespace="karyasampadan")),
    url(r'^comments/', include("comments.urls", namespace="comments")),
    url(r'^forms/', include("forms.urls", namespace="forms")),
              ] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
urlpatterns += url(r'^$', DashboardView.as_view(), name='dashboard'),


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ] + urlpatterns

office/urls.py
from django.conf.urls import url


from office.views import  OfficeDetailView, \
    OfficeUserView, OfficeBudgetUpdateView

app_name = 'office'

from office.views import OfficeCreateView, OfficeListView, OfficeUpdateView, OfficeDeleteView,\
    OfficeAddOfficeHeadView, OfficeAddInfoofficerView, Monthly, OfficeDashboard, DistrictDashboard, ProfileDetailView, ProfileUpdateView, OfficeKaryakramList,\
    OfficeViewDataDetail, OfficePragati


urlpatterns = [

    url(r'^office/create/$', OfficeCreateView.as_view(), name='office-add'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/$', OfficeDashboard.as_view(), name='office-dashboard'),
    url(r'^office/pragati/(?P<pk>[0-9]+)/$', OfficePragati.as_view(), name='office-pragati'),
    url(r'^office/detail/(?P<pk>[0-9]+)/$', OfficeDetailView.as_view(), name='office-detail'),
    url(r'^office/view-data-detail/(?P<pk>[0-9]+)/$', OfficeViewDataDetail.as_view(), name='view-data-detail'),
    url(r'^office/users/(?P<pk>[0-9]+)/$', OfficeUserView.as_view(), name='office-users'),

    url(r'^district/dashbaord/(?P<pk>[0-9]+)/$', DistrictDashboard.as_view(), name='district-dashboard'),
    url(r'^office/dashboard/(?P<pk>[0-9]+)/karyakramlist/$', OfficeKaryakramList.as_view(), name='office-karyakram-list'),
    url(r'^office/update/(?P<pk>[0-9]+)/$', OfficeUpdateView.as_view(), name='office-update'),
    url(r'^office/delete/(?P<pk>[0-9]+)/$', OfficeDeleteView.as_view(), name='office-delete'),
    url(r'^office/list/$', OfficeListView.as_view(), name='office-list'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addofficehead/$', OfficeAddOfficeHeadView.as_view(), name='office-add-office-head'),
    url(r'^office/(?P<pk>[0-9]+)/adduser/addinfoofficer/$', OfficeAddInfoofficerView.as_view(), name='office-add-info-officer'),
    #url(r'^office/(?P<pk>[0-9]+)/addtype/$', OfficeAddUserView.as_view(), name='office-addtype'),
    
    url(r'^office/addbudget/(?P<pk>[0-9]+)/$', OfficeBudgetUpdateView.as_view(), name='office-budget-update'),
    url(r'^deactivate_user/$', ProfileUpdateView.as_view(), name='deactivate-users'),
    url(r'^office/users/profile_update/(?P<pk>[0-9]+)/$', ProfileUpdateView.as_view(), name='profile-update'),
    url(r'^office/users/profile_detail/(?P<pk>[0-9]+)/$', ProfileDetailView.as_view(), name='profile-detail'),
    url(r'^office/monthly/$', Monthly.as_view(), name='monthly-report'),
    

        ]

progressmonitoring/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.conf.urls import include, url
from django.contrib.auth import views as auth_views
from django.conf import settings
from supa import views as core_views

from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^supa/', include('supa.urls')),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        core_views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'registration/login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'registration/Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'registration/Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'registration/Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', core_views.firstlogin, name='firstlogin'),    
]

if settings.DEBUG:
  urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT) 
  urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)  

users/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views
from . import views

app_name = 'users'

urlpatterns = ([
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        views.activate, name='activate'),
    url(r'^login/$', auth_views.login, {'template_name': 'login.html'}, name='login'),
    url(r'^logout/$', auth_views.logout,  {'next_page': '/users/login/'}, name='logout'),
    url(r'^password_reset/$', auth_views.password_reset, name='password_reset'),
    url(r'^password_reset/done/$', auth_views.password_reset_done, {'template_name': 'Password_reset_done.html'}, name='password_reset_done'),
    url(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        auth_views.password_reset_confirm, {'template_name': 'Password_reset_confirm.html'}, name='password_reset_confirm'),
    url(r'^reset/done/$', auth_views.password_reset_complete, {'template_name': 'Password_reset_complete.html'}, name='password_reset_complete'),
    url(r'^firstlogin/$', views.firstlogin, name='firstlogin'),
    url(r'^changefiscalyear/$', views.changefiscalyear, name='changefiscalyear')
    
])

supa/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User, Group
from django.db import models
from django.utils.translation import gettext as _
from django.db.models.signals import post_save
from django.dispatch import receiver
import datetime
class Post(models.Model):
	post = models.TextField(max_length=30)
	value = models.TextField(max_length=30)

	def __str__(self):
		return self.post



class Office(models.Model):
	name = models.CharField(max_length=255)
	address = models.CharField(max_length=255, blank=True)
	district = models.CharField(max_length=255, blank=True)
	email = models.CharField(max_length=255, blank=True)
	phone = models.CharField(max_length=255, blank=True)
	fax = models.CharField(max_length=255, blank=True)
	yearly_budget = models.CharField(max_length=255, blank=True)
	office_time = models.CharField(max_length=255, blank=True)
	no_of_workers = models.CharField(max_length=255, blank=True)
	vehicle = models.CharField(max_length=255, blank=True)
	head_name = models.CharField(max_length=255, blank=True)
	head_post = models.CharField(max_length=255, blank=True)
	head_phone_no = models.CharField(max_length=255, blank=True)
	head_assign_date = models.CharField(max_length=255, blank=True)
	head_act_time = models.CharField(max_length=255, blank=True)
	infoofficer_name = models.CharField(max_length=255, blank=True)
	infoofficer_post = models.CharField(max_length=255, blank=True)
	infoofficer_phone_no = models.CharField(max_length=255, blank=True)
	infoofficer_assign_date = models.CharField(max_length=255, blank=True)
	infoofficer_act_time = models.CharField(max_length=255, blank=True)
	accountant_name = models.CharField(max_length=255, blank=True)
	accountant_post = models.CharField(max_length=255, blank=True)
	accountant_phone_no = models.CharField(max_length=255, blank=True)
	accountant_assign_date = models.CharField(max_length=255, blank=True)
	accountant_act_time = models.CharField(max_length=255, blank=True)

	OPMimage = models.ImageField(upload_to='ompimage', null=True, blank=True)


	def __unicode__(self):
		return u'%s'%(self.name)




class Profile(models.Model):
	user = models.OneToOneField(User, on_delete=models.CASCADE)
	Offices = models.ForeignKey(Office, on_delete=models.CASCADE, blank=True, null=True)
	email_isconfirmed = models.BooleanField(default=False)
	#post = models.ForeignKey(Post, on_delete=models.CASCADE, default='4')
	name = models.CharField(max_length=30, blank=True)
	phoneno = models.CharField(max_length=30, blank=True)

	assign_date = models.DateField(null=True, blank=True)
	birth_date = models.DateField(null=True, blank=True)
	#photo_url = models.CharField(max_length=30, null=True)
	photo = models.ImageField(null=True, blank=True)


	def __str__(self):
		return str(self.user)

@receiver(post_save, sender=User)
def update_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)
    instance.profile.save()



class GroupProfile(models.Model):
    group = models.OneToOneField(Group, unique=True)
    level = models.IntegerField(primary_key=True)
    
    def __str__(self):
		return str(self.group)
# Create your models here.


class Form(models.Model):

	#name = models.CharField(max_length=30)
	formtype = models.CharField(max_length=10, blank=True)

	title = models.TextField(blank=True)
	karchasirsak = models.TextField(blank=True)
	ekai = models.CharField(max_length=30, blank=True)
	Office = models.ForeignKey(Office, on_delete=models.CASCADE)
	createdon = models.DateField(_("Date"), default=datetime.date.today)
	updatedon = models.DateField(default=datetime.date.today)
	def __unicode__(self):
		return u'%s'%(self.title)

# @receiver(post_save, sender=Form)
# def update_forms(sender, instance, created, **kwargs):
#     if created:
#     	if instance.formtype == "Project":
#     		a = Form.formtype
#     		# Currentacts.objects.create(form=instance)
#     		# Allacts.objects.create(form=instance)
#     		# instance.currentacts.save()
#     		# instance.allacts.save()
        
#     	# Yearly.objects.create(form=instance)
#     	# First.objects.create(form=instance)
#      #    Second.objects.create(form=instance)
#      #    Third.objects.create(form=instance)
#         Form_status.objects.create(form=instance)
#     # instance.yearly.save()
#     # instance.first.save()
#     # instance.second.save()
#     # instance.third.save()
#     instance.form_status.save()




class Yearly(models.Model):
	form = models.OneToOneField(Form, unique=True)
	parinam_aim = models.CharField(max_length=30, blank=True)
	bhar_aim = models.CharField(max_length=30, blank=True)
	budget_aim = models.CharField(max_length=30, blank=True)
	
	parinam_progress = models.CharField(max_length=30, blank=True)
	bhar_progress = models.CharField(max_length=30, blank=True)
	laagat_progress = models.CharField(max_length=30, blank=True)


	createdon = models.DateField(_("Date"), default=datetime.date.today)
	updatedon = models.DateField(default=datetime.date.today)

	def __unicode__(self):
		return u'%s'%(self.form.title)

class First(models.Model):
	form = models.OneToOneField(Form, unique=True)

	parinam_aim = models.CharField(max_length=30, blank=True)
	bhar_aim = models.CharField(max_length=30, blank=True)
	budget_aim = models.CharField(max_length=30, blank=True)
	
	parinam_progress = models.CharField(max_length=30, blank=True)
	bhar_progress = models.CharField(max_length=30, blank=True)
	laagat_progress = models.CharField(max_length=30, blank=True)

	createdon = models.DateField(_("Date"), default=datetime.date.today)
	updatedon = models.DateField(default=datetime.date.today)

	def __unicode__(self):
		return u'%s'%(self.form.title)

class Second(models.Model):
	form = models.OneToOneField(Form, unique=True)

	parinam_aim = models.CharField(max_length=30, blank=True)
	bhar_aim = models.CharField(max_length=30, blank=True)
	budget_aim = models.CharField(max_length=30, blank=True)
	
	parinam_progress = models.CharField(max_length=30, blank=True)
	bhar_progress = models.CharField(max_length=30, blank=True)
	laagat_progress = models.CharField(max_length=30, blank=True)


	createdon = models.DateField(_("Date"), default=datetime.date.today)
	updatedon = models.DateField(default=datetime.date.today)

	def __unicode__(self):
		return u'%s'%(self.form.title)

class Third(models.Model):
	form = models.OneToOneField(Form, unique=True)

	parinam_aim = models.CharField(max_length=30, blank=True)
	bhar_aim = models.CharField(max_length=30, blank=True)
	budget_aim = models.CharField(max_length=30, blank=True)
	
	parinam_progress = models.CharField(max_length=30, blank=True)
	bhar_progress = models.CharField(max_length=30, blank=True)
	laagat_progress = models.CharField(max_length=30, blank=True)


	createdon = models.DateField(_("Date"), default=datetime.date.today)
	updatedon = models.DateField(default=datetime.date.today)

	def __unicode__(self):
		return u'%s'%(self.form.title)


class Form_status(models.Model):
	V_STATUS = (
		('v', 'verified'),
		('u', 'unverified'),
		)
	C_STATUS = (
		('c', 'complete'),
		('u', 'uncomplete'),
		)
	form = models.OneToOneField(Form, on_delete=models.CASCADE)
	v_status = models.CharField(max_length=1, choices=V_STATUS, default='u')
	C_status = models.CharField(max_length=1, choices=C_STATUS, default='u')

	def __unicode__(self):
		return u'%s'%(self.form.title)

templates/base.html
<!DOCTYPE html>
<html>
<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <title>{% block title %}fwdc{% endblock title %}</title>
        {% load static %}
    {% load filters %}

    <!-- Tell the browser to be responsive to screen width -->
  <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
  <!-- Bootstrap 3.3.7 -->
  <link rel="stylesheet" href="{% static 'dashboard/bootstrap/css/bootstrap.min.css' %}">
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.5.0/css/font-awesome.min.css">
  <!-- Ionicons -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ionicons/2.0.1/css/ionicons.min.css">
  <!-- Theme style -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/css/AdminLTE.min.css' %}">
  <!-- AdminLTE Skins. Choose a skin from the css/skins
       folder instead of downloading all of them to reduce the load. -->
  <link rel="stylesheet" href="{% static 'dashboard/dist/css/skins/_all-skins.min.css' %}">
  <!-- Morris chart -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/morris/morris.css' %}">
  <!-- jvectormap -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/jvectormap/jquery-jvectormap-1.2.2.css' %}">
  <!-- Date Picker -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/datepicker/datepicker3.css' %}">
  <!-- Daterange picker -->
  <link rel="stylesheet" href="{% static 'dashboard/plugins/daterangepicker/daterangepicker.css' %}">
  <!-- bootstrap wysihtml5 - text editor -->
  
  
{% block extra_css %}
{% endblock extra_css %}

  <!-- HTML5 Shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
  <!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->

  <!-- Google Font -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">


</head>



<body class="hold-transition skin-blue sidebar-mini">



<div class="wrapper">

  <header class="main-header">
    <!-- Logo -->
    <a href="index2.html" class="logo">
      <!-- mini logo for sidebar mini 50x50 pixels -->
      <span class="logo-mini"><b>A</b>LT</span>
      <!-- logo for regular state and mobile devices -->
      <span class="logo-lg"><b>FWDC</b></span>
    </a>
    <!-- Header Navbar: style can be found in header.less -->
    <nav class="navbar navbar-static-top">
      <!-- Sidebar toggle button-->
      <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
        <span class="sr-only">Toggle navigation</span>
      </a>

      <div class="navbar-custom-menu">
        <ul class="nav navbar-nav">


          <!-- User Account: style can be found in dropdown.less -->
          <li class="dropdown user user-menu">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <img src="{% static 'dashboard/dist/img/user2-160x160.jpg' %}" class="user-image" alt="User Image">
              <span class="hidden-xs">Alexander Pierce</span>
            </a>
            <ul class="dropdown-menu">
              <!-- User image -->
              <li class="user-header">
                <img src="{% static 'dashboard/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">

                <p>
                  Alexander Pierce - Web Developer
                  <small>Member since Nov. 2012</small>
                </p>
              </li>

              <li class="user-footer">
                <div class="pull-left">
                  <a href="#" class="btn btn-default btn-flat">Profile</a>
                </div>
                <div class="pull-right">
                  <a href="{% url 'users:logout' %}" class="btn btn-default btn-flat">Log out</a>
                </div>
              </li>
            </ul>
          </li>
          <!-- Control Sidebar Toggle Button -->

        </ul>
      </div>
    </nav>
  </header>
  <!-- Left side column. contains the logo and sidebar -->
  <aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="{% static 'dashboard/dist/img/user2-160x160.jpg' %}" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Alexander Pierce</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
          <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu" data-widget="tree">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="#">
            <i class="fa fa-dashboard"></i> <span>जिल्ला</span>
            <span class="pull-right-container">
              <i class="fa fa-angle-left pull-right"></i>
            </span>
          </a>
          <ul class="treeview-menu">
            {% for district in districts %}
            <li class="active"><a href="{% url 'office:district-dashboard' district.id %}"><i class="fa fa-circle-o"></i> {{ district }}</a></li>
            {% endfor %}

          </ul>
        </li>
        <li class="treeview">
          <a href="#">
            <i class="fa fa-files-o"></i>
            <span>आयोजना</span>
            <span class="pull-right-container">
              <span class="label label-primary pull-right">4</span>
            </span>
          </a>
          <ul class="treeview-menu">
                    {% for project in projects %}

            <li><a href="{% url 'office:office-dashboard' project.id %}"><i class="fa fa-circle-o"></i> {{ project }}</a></li>
                    {% endfor %}

          </ul>
        </li>
        <li>
          <a href="{% url 'office:office-add' %}">
            <i class="fa fa-th"></i> <span>कार्यालय थप्नुहोस </span>

            <span class="pull-right-container">
              <small class="label pull-right bg-green">new</small>
            </span>
          </a>
        </li>

          <ul class="treeview-menu">
            <li><a href="{% static 'pages/UI/general.html' %}"><i class="fa fa-circle-o"></i> General</a></li>
            <li><a href="{% static 'pages/UI/icons.html' %}"><i class="fa fa-circle-o"></i> Icons</a></li>
            <li><a href="{% static 'pages/UI/buttons.html' %}"><i class="fa fa-circle-o"></i> Buttons</a></li>
            <li><a href="{% static 'pages/UI/sliders.html' %}"><i class="fa fa-circle-o"></i> Sliders</a></li>
            <li><a href="{% static 'pages/UI/timeline.html' %}"><i class="fa fa-circle-o"></i> Timeline</a></li>
            <li><a href="{% static 'pages/UI/modals.html' %}"><i class="fa fa-circle-o"></i> Modals</a></li>
          </ul>



    </section>
    <!-- /.sidebar -->
  </aside>

  <!-- Content Wrapper. Contains page content -->
  <div class="content-wrapper">
  {% block content %}
      {% endblock content %}
  </div>
  <!-- /.content-wrapper -->
  <footer class="main-footer">
    <div class="pull-right hidden-xs">
      <b>Version</b> 2.4.0
    </div>
    <strong>Copyright &copy; 2014-2016 <a href="https://adminlte.io">Almsaeed Studio</a>.</strong> All rights
    reserved.
  </footer>


  <!-- Add the sidebar's background. This div must be placed
       immediately after the control sidebar -->
  <div class="control-sidebar-bg"></div>
</div>

    <!-- jQuery 3.1.1 -->
<!-- <script src="{% static 'dashboard/plugins/jQuery/jquery-3.1.1.min.js' %}"></script> -->
<!-- jQuery UI 1.11.4 -->
<!-- <script src="https://code.jquery.com/ui/1.11.4/jquery-ui.min.js' %}"></script> -->
<!-- Resolve conflict in jQuery UI tooltip with Bootstrap tooltip -->
<script>
  $.widget.bridge('uibutton', $.ui.button);
</script>
<!-- Bootstrap 3.3.7 -->
<script src="{% static 'dashboard/bootstrap/js/bootstrap.min.js' %}"></script>
<!-- Morris.js charts -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js' %}"></script>
<script src="{% static 'dashboard/plugins/morris/morris.min.js"></script>
<!-- Sparkline -->
<script src="{% static 'dashboard/plugins/sparkline/jquery.sparkline.min.js' %}"></script>
<!-- jvectormap -->
<script src="{% static 'dashboard/plugins/jvectormap/jquery-jvectormap-1.2.2.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/jvectormap/jquery-jvectormap-world-mill-en.js' %}"></script>
<!-- jQuery Knob Chart -->
<script src="{% static 'dashboard/plugins/knob/jquery.knob.js"></script>
<!-- daterangepicker -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.11.2/moment.min.js' %}"></script>
<script src="{% static 'dashboard/plugins/daterangepicker/daterangepicker.js"></script>
<!-- datepicker -->
<script src="{% static 'dashboard/plugins/datepicker/bootstrap-datepicker.js' %}"></script>
<!-- Bootstrap WYSIHTML5 -->
<script src="{% static 'dashboard/plugins/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js' %}"></script>
<!-- Slimscroll -->
<script src="{% static 'dashboard/plugins/slimScroll/jquery.slimscroll.min.js' %}"></script>
<!-- FastClick -->
<script src="{% static 'dashboard/plugins/fastclick/fastclick.js' %}"></script>
<!-- AdminLTE App -->
<script src="{% static 'dashboard/dist/js/adminlte.min.js' %}"></script>
<!-- AdminLTE dashboard demo (This is only for demo purposes) -->
<script src="{% static 'dashboard/dist/js/pages/dashboard.js' %}"></script>
<!-- AdminLTE for demo purposes -->
<script src="{% static 'dashboard/dist/js/demo.js' %}"></script>

{% block extra_script %}
{% endblock extra_script %}

</body>
</html>